const providers = [
{name:'OpenAI',family:'Teks, generasi gambar, serta audio dan text-to-speech untuk aplikasi Anda.',discount:20,logo:'ChatGPT'},
{name:'Anthropic',family:'Akses keluarga model Claude melalui TokenKu.',discount:20,logo:'Claude'},
{name:'Google',family:'Pilihan AI untuk teks, gambar, dan video dalam alur kerja tim Anda.',discount:20,logo:'Gemini'},
{name:'DeepSeek',family:'Pilihan model untuk kebutuhan AI perusahaan.',discount:25,logo:'Deepseek'},
{name:'Alibaba',family:'Pilihan model teks serta generasi dan pengolahan video.',discount:25,logo:'Qwen'},
{name:'xAI',family:'Pilihan AI untuk teks, generasi gambar, dan video.',discount:20,logo:'Grok'},
{name:'ByteDance',family:'Generasi gambar dan video untuk kampanye serta produksi konten.'},
{name:'Zhipu',family:'Diskusikan pilihan model yang sesuai kebutuhan.'},
{name:'MiniMax',family:'Diskusikan pilihan model yang sesuai kebutuhan.'},
{name:'Moonshot',family:'Diskusikan pilihan model yang sesuai kebutuhan.'},
{name:'SUNO',family:'Generasi musik dan lirik untuk eksplorasi ide serta kebutuhan konten.'},
{name:'XiaomiMiMO',family:'Transkripsi audio menjadi teks untuk pengolahan informasi dan konten.'},
{name:'Tencent',family:'Diskusikan pilihan model yang sesuai kebutuhan.'},
{name:'Kling',family:'Pilihan generasi gambar dan video untuk produksi kreatif.'},
{name:'Midjourney',family:'Generasi dan pengolahan gambar, serta pilihan generasi video.'}
];
const featuredOrder=['OpenAI','Anthropic','Google','Midjourney','Kling','SUNO'];
providers.sort((a,b)=>(featuredOrder.includes(a.name)?featuredOrder.indexOf(a.name):99)-(featuredOrder.includes(b.name)?featuredOrder.indexOf(b.name):99));
const el=id=>document.getElementById(id);
let allProviders=false,providerFilter='all';
function renderProviders(){const term=el('provider-search').value.trim().toLowerCase();const list=providers.filter(p=>(providerFilter==='all'||p.discount)&&p.name.toLowerCase().includes(term));const visible=allProviders||term||providerFilter==='discount'?list:list.slice(0,6);el('provider-grid').innerHTML=visible.map(p=>`<article class="provider-card"><div class="provider-top"><span class="provider-symbol">${p.logo?`<img src="assets/Logo-Card_${p.logo}.svg" alt="" width="32" height="32">`:p.name.slice(0,2)}</span>${p.discount?`<span class="discount">Hemat hingga ${p.discount}%*</span>`:'<span class="available">Tersedia di TokenKu</span>'}</div><h3>${p.name}</h3><p>${p.family}</p><div class="provider-bottom"><span>Akses via TokenKu</span><button class="text-button" data-provider="${p.name}">Minta penawaran</button></div></article>`).join('');el('provider-empty').hidden=!!visible.length;el('show-providers').hidden=!!term||providerFilter==='discount';el('show-providers').textContent=allProviders?'Tampilkan provider utama':'Lihat semua 15 provider';}
el('provider-search').addEventListener('input',renderProviders);el('show-providers').addEventListener('click',()=>{allProviders=!allProviders;renderProviders()});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{providerFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-pressed',String(t===b))});renderProviders()}));renderProviders();
if(!industries[0].agents.includes('Enterprise Workflow Supervisor'))industries[0].agents.splice(6,0,'Enterprise Workflow Supervisor');
const industryCopy={
'Lintas industri':['Bantu tim melayani pelanggan, menemukan informasi internal, dan memproses dokumen lebih efisien.',['Layanan pelanggan','Pengetahuan internal','Pengolahan dokumen'],['Menjawab pertanyaan rutin dan membantu mengarahkan kasus ke tim yang tepat.','Membantu tim menemukan jawaban dari sumber informasi perusahaan.','Membantu membaca, mengekstrak, dan merangkum informasi dokumen.']],
'UKM':['Mulai dari pekerjaan harian yang paling menyita waktu, dari respons pelanggan hingga pengelolaan stok.',['Respons awal','Layanan pelanggan','Operasional stok']],
'Perbankan & keuangan':['Jajaki peluang mempercepat pelayanan, onboarding, dan pemeriksaan dokumen dengan kontrol yang sesuai.',['Layanan nasabah','Onboarding','Verifikasi dokumen']],
'Asuransi':['Bantu tim memahami dokumen polis, melayani nasabah, dan meninjau kebutuhan kepatuhan.',['Layanan nasabah','Dokumen polis','Kepatuhan']],
'Telekomunikasi & ISP':['Jajaki AI untuk layanan pelanggan, komunikasi gangguan, serta akses pengetahuan jaringan.',['Layanan pelanggan','Komunikasi gangguan','Pengetahuan jaringan']],
'Ritel & e-commerce':['Bantu tim melayani pelanggan, menjaga konsistensi operasional toko, dan menangani pengembalian barang.',['Layanan pelanggan','Operasional toko','Proses retur']],
'Makanan & minuman':['Temukan peluang meningkatkan layanan, memahami masukan pelanggan, dan mengelola operasional outlet.',['Layanan pelanggan','Masukan pelanggan','Operasional outlet']],
'Logistik & transportasi':['Jajaki peluang menangani pertanyaan pengiriman, memantau operasional, dan merencanakan rute.',['Layanan pengiriman','Visibilitas operasional','Perencanaan rute']],
'Manufaktur':['Identifikasi peluang efisiensi biaya, perencanaan produksi, dan akses pengetahuan pabrik.',['Efisiensi biaya','Jadwal produksi','Pengetahuan pabrik']],
'Tambang & industri berat':['Bantu tim mengakses pengetahuan lokasi, meninjau kegiatan operasional, dan menyiapkan pergantian shift.',['Operasional tambang','Serah terima shift','Pengetahuan lokasi']],
'Energi & utilitas':['Jajaki dukungan AI untuk layanan pelanggan, efisiensi energi, dan proses kepatuhan.',['Layanan pelanggan','Efisiensi energi','Kepatuhan']],
'Kesehatan & farmasi':['Bantu pekerjaan administrasi, penjadwalan, dan pencarian referensi dengan tinjauan tenaga profesional.',['Administrasi pendapatan','Penjadwalan','Referensi pengetahuan']],
'Properti & real estat':['Bantu pengelola melayani penghuni dan menindaklanjuti permintaan pemeliharaan.',['Informasi properti','Layanan penghuni','Pemeliharaan']],
'Pemerintahan & publik':['Jajaki pemrosesan dokumen, pencarian pengetahuan publik, dan dukungan peninjauan kepatuhan.',['Pengolahan dokumen','Kepatuhan','Pengetahuan publik']]
};
let selectedIndustry=0;
el('industry-list').innerHTML=industries.map((g,i)=>`<button data-industry="${i}" aria-pressed="${i===0}">${g.name}</button>`).join('');el('industry-select').innerHTML=industries.map((g,i)=>`<option value="${i}">${g.name}</option>`).join('');
function selectIndustry(i){selectedIndustry=i;const g=industries[i],c=industryCopy[g.name];el('industry-title').textContent=g.name;el('agent-count').textContent=g.agents.length+' rekomendasi';el('industry-description').textContent=c[0];el('industry-select').value=i;document.querySelectorAll('[data-industry]').forEach(b=>{const active=Number(b.dataset.industry)===i;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});el('agent-featured').innerHTML=g.agents.slice(0,3).map((a,j)=>`<article class="agent-card"><span>${c[1][j].toUpperCase()}</span><h4>${a}</h4><p>${c[2]?.[j]||'Ruang lingkup, kebutuhan data, dan manfaat ditentukan bersama melalui diskusi kelayakan.'}</p><button class="text-button" data-agent="${a}">Diskusikan use case</button></article>`).join('');el('agent-list').innerHTML=g.agents.map(a=>`<button data-agent="${a}">${a}</button>`).join('');document.querySelector('.agent-details').open=false;}
document.querySelectorAll('[data-industry]').forEach(b=>b.addEventListener('click',()=>selectIndustry(Number(b.dataset.industry))));el('industry-select').addEventListener('change',e=>selectIndustry(Number(e.target.value)));selectIndustry(0);
const dialog=el('enquiry-dialog'),form=el('enquiry-form');let lastTrigger=null;
function openEnquiry(type,message=''){lastTrigger=document.activeElement;form.hidden=false;el('form-result').hidden=true;el('enquiry-type').value=type;form.elements.pesan.value=message;el('form-title').textContent=type==='Akun perusahaan'?'Ajukan akun perusahaan':type==='Penawaran provider AI'?'Minta penawaran AI':'Diskusikan kebutuhan AI';dialog.showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-enquiry],[data-provider],[data-agent]');if(!b)return;if(b.dataset.enquiry)openEnquiry(b.dataset.enquiry,b.dataset.prefill||'');else if(b.dataset.provider)openEnquiry('Penawaran provider AI','Saya ingin mendapatkan penawaran akses provider '+b.dataset.provider+'.');else openEnquiry('Konsultasi solusi AI','Saya tertarik mendiskusikan '+b.dataset.agent+' untuk kategori '+industries[selectedIndustry].name+'.');});el('industry-enquiry').addEventListener('click',()=>openEnquiry('Konsultasi solusi AI','Saya ingin mendiskusikan solusi AI untuk '+industries[selectedIndustry].name+'.'));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>lastTrigger?.focus());
form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);el('request-summary').textContent=['PERMINTAAN TOKENKU.AI','Nama: '+d.get('nama'),'Perusahaan: '+d.get('perusahaan'),'Email: '+d.get('email'),'WhatsApp: '+d.get('telepon'),'Kebutuhan: '+d.get('kebutuhan'),'Jenis bisnis: '+(d.get('jenis_bisnis')||'Belum diisi'),'Estimasi per bulan: '+(d.get('estimasi')||'Belum diisi'),'Catatan: '+d.get('pesan'),'','Status: draf, belum dikirim ke sales.'].join('\n');form.hidden=true;el('form-result').hidden=false;el('download-request').focus()});el('edit-request').addEventListener('click',()=>{form.hidden=false;el('form-result').hidden=true;form.elements.nama.focus()});el('download-request').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([el('request-summary').textContent],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Permintaan-TokenKu.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Tutup navigasi':'Buka navigasi');menu.textContent=open?'×':'☰'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Buka navigasi');menu.textContent='☰'}));
